### ISSUE TITLE
Use BFS for traversing links

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#102]
Implement BFS for web crawling URLs, we currently only search the URL that is passed to TorBot for links on that page. We'd like to search them as a graph using BFS.

**Comment by KingAkeem** [comment]
I'm going to begin working on this soon.

**Comment by PSNAppz** [comment]
@KingAkeem Ok Great.

**Comment by KingAkeem** [comment]
I think I'm going to work on switching to Twisted instead since we really need performance to make the `-l` flag usable.
