### ISSUE TITLE
Design GUI for TorBot

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#113]
I think we should create a  GUI for TorBot to make it more user-friendly using something like Electron (JavaScript) possibly? I think it'd be a good framework because of the pure popularity so it'll be easy to find contributors and it's supposedly very productive so we'll be able to get out a version very soon.

**Comment by KingAkeem** [comment]
Would you like to help tackle this project?

**Comment by Z3N00** [comment]
yes

**Comment by KingAkeem** [comment]
Awesome, are you experienced with JavaScript and using the Electron framework in particular?

**Comment by KingAkeem** [comment]
We're planning to use Vue with Electron, does anyone have experience with Vue?

**Comment by PSNAppz** [comment]
@Z3N00 Would you like to get an invitation for our slack channel ?

**Comment by Z3N00** [comment]
Yes sure

**Comment by PSNAppz** [comment]
Drop your email please.

**Comment by Z3N00** [comment]
kartikgupta676@gmail.com
same email

**Comment by PSNAppz** [comment]
Ok. will send you an invite now

**Comment by mariogomesbarbosa** [comment]
Hello, if still needing help with GUI, I'm an UX Designer and I'm exciting to be helping with this project. And I have a tween brother (lol but is true) that have experience with Vue.js. If you want invite me to slack channel, end we talk about it.
mariogomesbarbosa@gmail.com

**Comment by atlking-Novetta** [comment]
@mariogomesbarbosa Awesome, super excited to have some experienced designers on board and we could definitely use the help in the upcoming project. I'll invite you to the slack now!

**Comment by KingAkeem** [comment]
You've been invited to the channel! Thanks for the help

**Comment by PSNAppz** [comment]
@mariogomesbarbosa @Z3N00 Did you guys join the channel?

**Comment by KingAkeem** [comment]
Yes they are both in the channel

**Comment by PSNAppz** [comment]
Great !
We'll have to discuss about the GUI. @KingAkeem You can create a separate channel #GUI for this.

**Comment by PSNAppz** [comment]
@KingAkeem Should I close this?

**Comment by KingAkeem** [comment]
It's really still in progress but you can close it since the project is in a different repo.
