### ISSUE TITLE
Invalid Syntax in savedb.py

### ISSUE THREAD

**Issue by DocKali** [DedSecInside/TorBot#115]
Hi guys,

First of all, thank you for handling this project which seems really interesting.

When I try to test your tool, I have an error concerning savedb.py. Here is the traceback I have : 

> Traceback (most recent call last):
>   File "torBot.py", line 6, in <module>
>     from modules import (bcolors, getemails, pagereader, getweblinks, updater,
>   File "/usr/toolz/TorBot/modules/savedb.py", line 31
>     print "Error '{0}' occurred. Arguments {1}.".format(e.message, e.args):
>                                                ^
> SyntaxError: invalid syntax

Did the mistake came from my side and you can I solve that?

Thank you for your help!

EDIT :  Just saw that this error will be corrected in TorBot 1.3, am I right?

**Comment by PSNAppz** [comment]
@DocKali Thanks for the issue. Unfortunately for you its already fixed.

**Comment by DocKali** [comment]
If the issue is fixed, why did I have always this error message? I just made a git pull and my version of your tool is up-to-date...

**Comment by PSNAppz** [comment]
@DocKali Thanks for pointing that out. The fix is yet to be merged.
