### ISSUE TITLE
Problem when running torBot binary

### ISSUE THREAD

**Issue by DocKali** [DedSecInside/TorBot#116]
Hi,
When I try to run TorBot binary, I obtain an error and the tool stop. Here is the traceback : 

```
Traceback (most recent call last):
  File "torBot.py", line 5, in <module>
    import settings
  File "/tmp/pip-install-Xz8Ej3/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "settings.py", line 4, in <module>
    load_dotenv(dotenv_path=env_path)
  File "dotenv/main.py", line 255, in load_dotenv
  File "dotenv/main.py", line 95, in set_as_environment_variables
  File "dotenv/main.py", line 74, in dict
  File "collections.py", line 69, in __init__
  File "_abcoll.py", line 571, in update
  File "dotenv/main.py", line 79, in parse
  File "dotenv/main.py", line 60, in _get_stream
  File "genericpath.py", line 26, in exists
TypeError: coercing to Unicode: need string or buffer, PosixPath found
[2568] Failed to execute script torBot
```

Do you know how to solve this?

Thanks for your help!

**Comment by PSNAppz** [comment]
@KingAkeem Please take a look at this.

**Comment by PSNAppz** [comment]
@DocKali Its not the issue of binary.
Could you provide us the exact option/input you gave to torBot ?

**Comment by DocKali** [comment]
@PSNAppz Of course, it was a classical test of your tool. The syntax was python3 torBot.py -u sitename.onion
It test this input with several sites, and I have the result described above everytime.

**Comment by PSNAppz** [comment]
@DocKali I cannot reproduce this.

**Comment by DocKali** [comment]
Strange... I'll make more test to see if I can reproduce that.
Oups, I made a mistake in my first response to your demand. The syntax I used is of course ./torBot -u siteadresse.onion, not python3 -u siteadresse.onion.

**Comment by PSNAppz** [comment]
@DocKali Ok but both has the same effect.

**Comment by KingAkeem** [comment]
@DocKali Have you tried installing the requirements via `pip3 install -r requirements.txt`?

**Comment by DocKali** [comment]
Thanks @KingAkeem for your help.

I did a python3 -m pip install -r requirements.txt and all requirements were already satisfied. 
I try to run your tool with some random onion sites but always the same error that I described in my first message...

**Comment by KingAkeem** [comment]
Did you do a `git pull` beforehand, because I think the requirement was added after your issue was opened. Also try using `pip3 install -r requirements.txt` rather than `python3 -m pip install -r reqiurements.txt`

**Comment by DocKali** [comment]
I just made a git pull and it appears that the version I had of TorBot is up-to-date. Following your recommandations I use pip3 install -r requirements.txt and all requirements are already satisfied. If you need screenshots, I can provide them of course.

**Comment by KingAkeem** [comment]
What system are you using? Is it a Windows machine?

**Comment by DocKali** [comment]
Hey @KingAkeem Sorry for this late answer. Here are the requested informations : 
- OS : kali-rolling
- Browser : Firefox ESR

Hope this will help you...

**Comment by KingAkeem** [comment]
The problem should no longer exists, we removed the module using `python-dotenv` from TorBot. Do you have any files that stlll using `python-dotenv`? If so then you need to perform a `git pull`. Does that make sense? If you take a look at the error message, it's tell you that it's an issue with `dotenv` but we're no longer using this so that message doesn't make sense if you have the latest version of TorBot.

**Comment by PSNAppz** [comment]
@DocKali #119 Should fix this issue. Please let us know if the problem still exists. Thank you.
