### ISSUE TITLE
Feature/Idea Suggestions!!

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#120]
All suggestions are welcome. Let's talk about what you'd like to see be added to TorBot and we can work on incorporating it into v2. This will be used to track your suggestions.

**Comment by PSNAppz** [comment]
• Metadata extractor
• Image grabber

**Comment by PSNAppz** [comment]
Ok. I will edit my comment and add the details there itself then.

**Comment by shashwat1002** [comment]
I think extracting the title for each webpage will be a good addition to the tree. I am willing to work on this.

**Comment by PSNAppz** [comment]
@shashwat1002 Great! You can start working on it.

**Comment by KingAkeem** [comment]
@shashwat1002 Sounds good, let us know if you need assistance.

**Comment by alan-raff** [comment]
Hi team, great work with this project. Very impressive. I'm curious, do you plan to add a feature where we can somehow authenticate to an onion service before scanning, as most links/info on many DNMs will be protected with a login system. Keep up the great work!

**Comment by KingAkeem** [comment]
We don't have plans of implementing such a feature. Would you be willing to work on it?

**Comment by danieleperera** [comment]
Hi guys, have you got any plans to add Raw Protocol Info e.g. SSH Key, SSH Fingerprint and Software Banner ? Keep up the great work!
