### ISSUE TITLE
TypeError: hasattr expected 2 arguments, got 3

### ISSUE THREAD

**Issue by 42B** [DedSecInside/TorBot#130]
https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/utils.py#L84

```python
>>> hasattr(str, 'replace')
True
>>> hasattr(str, 'replace', False)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: hasattr expected 2 arguments, got 3
```

https://docs.python.org/3/library/functions.html#hasattr

**Comment by KingAkeem** [comment]
This is a syntax error, would you like to submit a PR to fix this?

**Comment by KingAkeem** [comment]
This has been solved.
