### ISSUE TITLE
cprint's broken?

### ISSUE THREAD

**Issue by 42B** [DedSecInside/TorBot#131]
**Describe the bug**
```python
# termcolor.py

def cprint(text, color=None, on_color=None, attrs=None, **kwargs):
    """Print colorize text.

    It accepts arguments of print function.
    """

    print((colored(text, color, on_color, attrs)), **kwargs)

```
How can `cprint` output properly with color without a comma separating the text and color?

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L12

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L16

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L20

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L24

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L28

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L32

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L45

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L53

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L58-L62

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L66

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L71-L75

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L79

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L84-L90

https://github.com/DedSecInside/TorBot/blob/fa8eb533d47a74188886c1c94558de750e75759a/modules/info.py#L95

**Comment by KingAkeem** [comment]
These are syntax errors, you can submit a PR to fix them if you would like. Otherwise, I'll handle it. Nice catch :+1:

**Comment by 42B** [comment]
@KingAkeem I'll send a PR right away
