### ISSUE TITLE
Add get_images to LinkNodes

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#140]
**Describe the solution you'd like**
Add a method to [LinkNode](https://github.com/KingAkeem/TorBot/blob/80b3cb4d35f915cab6551fdcc0b962c8197bbead/modules/link.py#L9) that retrieves all of the urls from a link and caches them, similarly to emails and other links

Other solutions are welcomed and will be considered.

**Comment by PSNAppz** [comment]
@KingAkeem Links to images ?
