### ISSUE TITLE
Set metadata for LinkNode

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#141]
**Describe the solution you'd like**
Extract metadata from HTTP response and set it to LinkNode properties

**Comment by OlgaCh** [comment]
Hi @PSNAppz 
if this issue still valid I'd like to work on it as a part of the `hacktoberfest` contribution.

**Comment by KingAkeem** [comment]
Yes this issue is still valid since we aren't currently storing the metadata from the response. Thank you for your interest in contributing, I'll assign the issue to you.
