### ISSUE TITLE
Invalid Connection header 

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBot#154]
Invalid Connection header: ['keep-alive'] when using `--server` flag [PR #152]

**Comment by KingAkeem** [comment]
This isn't an invalid connection header, it's valid for WebSocket connections. It's the whole point, https://tools.ietf.org/id/draft-thomson-hybi-http-timeout-01.html

**Comment by PSNAppz** [comment]
Closing the issue.
