### ISSUE TITLE
ImportError: No module named dis3 

### ISSUE THREAD

**Issue by Leejinjin** [DedSecInside/TorBot#155]
Hi. When I try to install TorBot on Kali linux(in Vmware) error occurs. 

`root@kali:~/Downloads/TorBot-dev# ./install.sh
Collecting pyinstaller
Requirement already satisfied: pefile>=2017.8.1 in /usr/lib/python2.7/dist-packages (from pyinstaller) (2018.8.8)
Collecting macholib>=1.8 (from pyinstaller)
  Using cached https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Collecting altgraph (from pyinstaller)
  Using cached https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from pyinstaller) (40.2.0)
Installing collected packages: altgraph, macholib, pyinstaller
Successfully installed altgraph-0.16.1 macholib-1.11 pyinstaller-3.4
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 79, in run
    import PyInstaller.building.build_main
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 33, in <module>
    from ..depend import bindepend
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/utils.py", line 25, in <module>
    from ..lib.modulegraph import util, modulegraph
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/lib/modulegraph/util.py", line 16, in <module>
    from ._compat import StringIO, BytesIO, get_instructions, _READ_MODE
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/lib/modulegraph/_compat.py", line 29, in <module>
    from dis3 import get_instructions
ImportError: No module named dis3
mv: cannot stat 'tmp_dist/torBot': No such file or directory
rm: cannot remove 'torBot.spec': No such file or directory
`

What am I missing? I try to find out but can't.

**Comment by PSNAppz** [comment]
Did you give enough permission to the shell script?

**Comment by KingAkeem** [comment]
@PSNAppz We need a docker container for TorBot to avoid these issues.

**Comment by KingAkeem** [comment]
@Leejinjin There seems to be an issue with pyinstaller, you can run torBot directly to avoid this issue using `python3 torBot.py` or `python torBot.py` if you have python3 as default.

**Comment by PSNAppz** [comment]
@KingAkeem We will create a docker image once we finish fixing the major bugs.

**Comment by m0neyy** [comment]
still open? would be first pull request but I have decent python skills and a bit of kali experience

**Comment by N1GHTPATROL** [comment]
Has this issue been fixed? I'm experiencing the same problem.

**Comment by KingAkeem** [comment]
Which version of Python are you using?

**Comment by KingAkeem** [comment]
Also what are the permissions on `install.sh`?

**Comment by KingAkeem** [comment]
Closing due to no response
