### ISSUE TITLE
Insallation issue on Kali 

### ISSUE THREAD

**Issue by betanc** [DedSecInside/TorBot#160]
**Describe the bug**
when i install torBot whith requirements.txt have this problem:

Collecting PyQt5==5.12.1 (from -r requirements.txt (line 9))
  Could not find a version that satisfies the requirement PyQt5==5.12.1 (from -r requirements.txt (line 9)) (from versions: )
No matching distribution found for PyQt5==5.12.1 (from -r requirements.txt (line 9))

I try install PyQt manually and don't work anyway...

Appreciate your help

**Comment by KingAkeem** [comment]
Have you tried `sudo apt-get install python-pyqt5` and do a pip install as well?

**Comment by KingAkeem** [comment]
Closing due to no response
