### ISSUE TITLE
Dockerize TorBot

### ISSUE THREAD

**Issue by v1shwa** [DedSecInside/TorBot#164]
- Dockerize Torbot to avoid issues like #155 .
- Entry point should `torbot` binary.

**Comment by v1shwa** [comment]
@PSNAppz I can take this up for Hacktoberfest , if it sounds cool. Please let me know.

**Comment by PSNAppz** [comment]
@v1shwa Sounds like a plan. Let me or @KingAkeem know if you need any help.
