### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by advanced4** [DedSecInside/TorBot#187]
**Describe the bug**
The README is lacking some basic information & detail

**Additional context**
- How do I even use this tool? Showing an example usage is worth a lot
  - Do I have to specify lots of URLs, each as a "-u" argument? That seems unfriendly - can I provide a file?
- The 'Working Procedure/Basic Plan' section looks great, just what I want. How do I actually get it to do that?
  - I've tried many combination of arguments, and none of them "store page content" - several don't work
- What does the "--gather" option do? The description of "gather data for analysis" couldn't be more ambiguous. What kind of data? Where is it storing it? What format is it in?
- The description of this program implies a database is used, but I see no mention of that. Or is one not used, and each run of the program is totally independent from previous runs? (See pseudo code "link is not visited" - how do you know what you previously saw?)

All of this lacking information is a barrier to entry to anyone who wants to use, let alone contribute to this project.

**Comment by PSNAppz** [comment]
@advanced4 Thanks for pointing this out. @masterugwee is working on an extensive documentation for the project. Hopefully, it’ll be added to the wiki page soon.
