### ISSUE TITLE
Unknown Cause of Connection Issue

### ISSUE THREAD

**Issue by orrj** [DedSecInside/TorBot#191]
Hello,

I'm not sure if this is the correct place to post this question, but I haven't been able to find any resolution through my online research.  When I try to run torBot.py, the program begins fine, then there are some connection errors, and the program eventually hangs and never finishes.  Below is the output I copied from the most recent attempt.  

I have torrc with the following uncommented:
SocksPort 9050
ControlPort 9051
CookieAuthentication 1

Thank you in advance for any help!

(torbot-project) admin@acer-lmde64:~/repos/TorBot/src$ python torBot.py -u http://answerstedhctbek.onion/ -i -m

                                    
                           __  ____  ____  __        ______
                          / /_/ __ \/ __ \/ /_  ____/_  __/
                         / __/ / / / /_/ / __ \/ __ \/ /
                        / /_/ /_/ / _, _/ /_/ / /_/ / /
                        \__/\____/_/ |_/_____/\____/_/  V1.4.0
              
                    #######################################################
                    #  TorBot - An OSINT Tool for Dark Web                #
                    #  GitHub : https://github.com/DedsecInside/TorBot    #
                    #  Help : use -h for help text                        #
                    #######################################################
                                  LICENSE: GNU Public License v3
              
Attempting to connect to https://check.torproject.org/
Tor IP Address: 176.10.99.200
['answers@muc.volatile.bz', 'answers@muc.volatile.bz']
[*]Checking for Robots.txt
http://answerstedhctbek.onion/robots.txt
[*]Checking for .git folder
NO .git folder found
[*]Checking for .svn folder
NO .SVN folder found
[*]Checking for .git folder
NO .git folder found
Intel
--------

BTC FOUND:  0
[*]Checking for meta tag
Meta :  <meta charset="utf-8"/>
Links Found - 8
---------------------------------
https://blog.torproject.org/v2-deprecation-timeline                 Onion Service version 2 deprecation timeline | Tor Blog
http://ru.answerszuvs3gg2l64e6hmnryudl5zgrmwm3vh65hzszdghblddvfiqd.onion/ Скрытые Ответы                
http://es.answerszuvs3gg2l64e6hmnryudl5zgrmwm3vh65hzszdghblddvfiqd.onion/ Respuestas Ocultas            
http://pt.answerszuvs3gg2l64e6hmnryudl5zgrmwm3vh65hzszdghblddvfiqd.onion/ Respostas Ocultas             
http://intel5vmppiwc4u6l5bisfdv7sazzlacrqcuze4wxqdavd5kltxru7qd.onion/ Intel Repository              
http://bv42dik6lu2ou3fyexeiy2y3eady3ldu2ow775l5anccgxpgqsw2jyyd.onion/doku.php Hidden Wiki Fresh             
Error connecting to Tor: HTTPConnectionPool(host='torum43tajnrxritn4iumy75giwb5yfw6cjq2czjikhtcac67tfif2yd.onion', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe686bd1f70>: Failed to establish a new connection: Socket error: 0x04: Host unreachable'))
Error connecting to Tor: HTTPConnectionPool(host='visitorfi5kl7q7i.onion', port=80): Max retries exceeded with url: /search (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe686bd13d0>: Failed to establish a new connection: Socket error: 0x06: TTL expired'))

**Comment by PSNAppz** [comment]
@orrj Thanks for reporting the bug, we are working on a major update and hopefully this will be fixed.
