### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by CYB3RMX** [DedSecInside/TorBot#209]
**Describe the bug**
I tried to execute program from terminal there is no error but when I try to open web interface and crawl any of onion links my browser throws connection refused error.

**To Reproduce**
1. Start tor service manually: ```sudo systemctl start tor.service```
2. Go to the torbot-frontend directory: ```cd src/torbot-frontend/```
3. Starting angular app with: ```ng serve --open```
4. Try to make simple request via web application

**Expected behavior**
Not any connection errors while crawling onion links

**Screenshots**
![tracker](https://user-images.githubusercontent.com/42123683/115971236-dda00180-a536-11eb-9bfa-ba646c2cac4e.png)

**Desktop (please complete the following information):**
 - OS:  Parrot OS
 - Browser: Chromium
 - Version: latest

**Comment by masterugwee** [comment]
The problem is due to not running the api.
Go to the src/api. 
You can find endpoints.py in the folder, run it. This will solve the issue. 

Steps to fix error: Once you run ng serve. In another terminal 
`cd src/api`
`python3 endpoints.py`

**Comment by CYB3RMX** [comment]
@masterugwee Thanks for the reply. I finally to open the program everything is fine but when I try to send any query I encounter this error:
![mali](https://user-images.githubusercontent.com/42123683/115991502-32379100-a5b8-11eb-8318-c9b216cfee3b.png)

**Comment by masterugwee** [comment]
Strange, I guess there might be some indentation error. Can you pull the update and try again.

**Comment by PSNAppz** [comment]
Seems like an issue with `LinkNode` @KingAkeem can you take a look at this?

**Comment by KingAkeem** [comment]
The `LinkNode` links` property was replaced with a `get_links` method so that the metadata could be loaded dynamically. It looks like the front-end code is still referencing the old `links` property instead of using the `get_links` method. I'm not familiar with the UI code but wherever the links are being pulled will need to use the `get_links` method instead of trying to access the `links` member variable.

**Comment by KingAkeem** [comment]
https://github.com/DedSecInside/TorBot/blob/f95eacc5f73bec8a83c059a3cb4b0b091ec7429c/src/modules/link.py#L119-L122 Here's a link to the `get_children` method. It will return a list of `LinkNode` objects which are the children of that node.

**Comment by KingAkeem** [comment]
I'd like to help out more here but I don't know how to use the GUI and there are no instructions, can anyone help out?

**Comment by KingAkeem** [comment]
Front-end is not ready for use
