### ISSUE TITLE
issue to start

### ISSUE THREAD

**Issue by BlAd373** [DedSecInside/TorBot#211]
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "modules/analyzer.py", line 6, in <module>
ModuleNotFoundError: No module named 'ete3'
[20299] Failed to execute script torBot

some suggestion?

**Comment by KingAkeem** [comment]
It looks like `ete3` hasn't been installed, have you tried using `pip install -r requirements.txt`

**Comment by KingAkeem** [comment]
[ete3](http://etetoolkit.org/) is a visualization library that is used to analyze and visualize link trees.

**Comment by BlAd373** [comment]
eta3 is installed but requirements.txt is not in the directory

**Comment by BlAd373** [comment]
i removed folder i reinstall from github now i receive this error
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
  File "/usr/local/lib/python3.9/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "modules/analyzer.py", line 6, in <module>
ImportError: cannot import name 'faces' from 'ete3' (/tmp/_MEIHaJnUe/ete3/__init__.pyc)
[43591] Failed to execute script torBot

**Comment by KingAkeem** [comment]
Which version of Python are you using? and what's our OS?

**Comment by BlAd373** [comment]
kali linux 2021.2 
Python 3.9

**Comment by BlAd373** [comment]
did you have some distro to suggest ?

**Comment by KingAkeem** [comment]
Apologies for the late reply but yes, I would recommend using Ubuntu 20.04.2 LTS or higher.

**Comment by KingAkeem** [comment]
Also are you on the latest branch?

**Comment by BlAd373** [comment]
witch one ?

**Comment by KingAkeem** [comment]
The latest version of `dev`, it's the main branch. https://github.com/DedSecInside/TorBot

**Comment by sniffski** [comment]
> Apologies for the late reply but yes, I would recommend using Ubuntu 20.04.2 LTS or higher. 

Same "ete3 error"... 

Release:
```
$ lsb_release -a                                                          No LSB modules are available.                                               Distributor ID: Ubuntu                                                      Description:    Ubuntu 20.04.3 LTS                                          Release:        20.04                                                       Codename:       focal
```
Error:
```
$ ./torBot
Traceback (most recent call last):
  File "torBot.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "modules/linktree.py", line 4, in <module>
ModuleNotFoundError: No module named 'ete3'
[9744] Failed to execute script 'torBot' due to unhandled exception!
```
Trying to run ete3:
```
$ ete3                                                                    Traceback (most recent call last):                                            File "/home/sniffski/.local/bin/ete3", line 5, in <module>                    from ete3.tools.ete import main                                           File "/home/sniffski/.local/lib/python3.8/site-packages/ete3/tools/ete.py", line 55, in <module>                                                          from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,                                                                          File "/home/sniffski/.local/lib/python3.8/site-packages/ete3/tools/ete_view.py", line 48, in <module>                                                     from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,                                                        ImportError: cannot import name 'TextFace' from 'ete3' (/home/sniffski/.local/lib/python3.8/site-packages/ete3/__init__.py)
```

Please help 🙏

**Comment by pulkit22** [comment]
Getting the same error, could anybody help.

**Comment by Fankaren** [comment]
My solution: (ubuntu20.04.3 LTS, python3)

> My python3 dependency: 
> beautifulsoup4
> pyinstaller
> PySocks
> termcolor
> requests
> requests_mock
> yattag
> lxml
> six
> numpy
> stem
> threadsafe
> progress
> validators

```
pip3 install PyQt5
wget https://github.com/etetoolkit/ete/archive/refs/tags/3.1.2.zip
unar 3.1.2.zip
cd ete-3.1.2
python3 setup.py install
```

Reference link: 
http://etetoolkit.org/download/

**Comment by EdgyIndexer** [comment]
I'm also receiving the same error after following all these steps

**Comment by parthk2510** [comment]
I am getting this error 

 File "c:\Users\91900\Downloads\TorBot-dev\src\torBot.py", line 10, in <module>
    from modules.linktree import LinkTree
  File "c:\Users\91900\Downloads\TorBot-dev\src\modules\linktree.py", line 5, in <module>
    from .utils import join_local_path
  File "c:\Users\91900\Downloads\TorBot-dev\src\modules\utils.py", line 7, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

can you share a video in which the bot is running ?
