### ISSUE TITLE
Attribute error  when using -d or -v

### ISSUE THREAD

**Issue by luke2103** [DedSecInside/TorBot#212]
When I run **python3 torBot.py -u http://duskgytldkxiuqc6.onion/ -d** or **python3 torBot.py -u http://duskgytldkxiuqc6.onion/** -v I get the below error 

> (venv) lukesh@pop-os:~/TorBot/src$ python3 torBot.py -u http://duskgytldkxiuqc6.onion/ -d

                                    
                           __  ____  ____  __        ______
                          / /_/ __ \/ __ \/ /_  ____/_  __/
                         / __/ / / / /_/ / __ \/ __ \/ /
                        / /_/ /_/ / _, _/ /_/ / /_/ / /
                        \__/\____/_/ |_/_____/\____/_/  V1.4.0
              
                    #######################################################
                    #  TorBot - An OSINT Tool for Dark Web                #
                    #  GitHub : https://github.com/DedsecInside/TorBot    #
                    #  Help : use -h for help text                        #
                    #######################################################
                                  LICENSE: GNU Public License v3

> Attempting to connect to https://check.torproject.org/
Tor IP Address: 185.220.101.135
Adding node for:  "Woooooooooooo!" -Roger"
Traceback (most recent call last):
  File "torBot.py", line 250, in <module>
    main()
  File "torBot.py", line 169, in main
    tree = LinkTree(node)
  File "/home/lukesh/TorBot/src/modules/analyzer.py", line 33, in __init__
    self._tree = build_tree(root_node, stop=stop_depth)
  File "/home/lukesh/TorBot/src/modules/analyzer.py", line 90, in build_tree
    if child.get_children():
  File "/home/lukesh/TorBot/src/modules/link.py", line 122, in get_children
    return self._children
AttributeError: 'LinkNode' object has no attribute '_children'

Can anyone help me fix this??

**Comment by KingAkeem** [comment]
Hey luke, I just merged a fix for this issue so you should be able to use the tree features again. I'm going to be taking a look at some potential issues so let me know if you need help with anything else.
