### ISSUE TITLE
Docker buld fails. Unable to find installation candidates for pyqt5-qt5 (5.15.2)

### ISSUE THREAD

**Issue by xxxcrow** [DedSecInside/TorBot#217]
**Describe the bug**
Docker build fails

**To Reproduce**
1. git clone [repo] && cd [repo]
2. docker build -f docker/Dockerfile -t dedsecinside/torbot .

**Expected behavior**
Ready docker image

**Comment by NeoLight1010** [comment]
That's weird. I can't reproduce the error 😕 
![image](https://user-images.githubusercontent.com/58057324/126017757-1d55ddd6-5d43-46e2-a02a-dbf997b7fd03.png)

**Comment by xxxcrow** [comment]
@NeoLight1010 oh, sorry, I probably was in hurry and didn't add the problem 😅
```
Installing soupsieve (2.2.1)

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.2)

  at /usr/local/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in ch
oose_for
       68│
       69│             links.append(link)
       70│
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(p
ackage)
       74│             )
       75│
       76│         # Get the best link
```

**Comment by othin1** [comment]
Same error with ubuntu desktop 21

**Comment by pulkit22** [comment]
Getting the Same error, have you got any solution?

**Comment by PSNAppz** [comment]
Disabled `ete3` for the time being since the library was causing many issues.
