### ISSUE TITLE
Installation Error - Need Help

### ISSUE THREAD

**Issue by qqbbpsy** [DedSecInside/TorBot#222]
![Screenshot_2021-10-14_06-37-56](https://user-images.githubusercontent.com/45928848/137302271-42575797-e642-4f47-b715-570b77cbd54b.png)

**Comment by qqbbpsy** [comment]
> I haven't used the installation file in a while so I'll check this out.

I tried pip3 install pyinstaller

Requirement already satisfied: pyinstaller in /usr/lib/python3/dist-packages (3.5+498e6ee058)

**Comment by qqbbpsy** [comment]
(**3.5+498e6ee058**)

**Comment by qqbbpsy** [comment]
i upgrade it and was successful but pyinstaller --version still shows version  (3.5+498e6ee058) ./installer.sh failed again with the same error

**Comment by KingAkeem** [comment]
I'd suggest figuring out how to upgrade your version of pyinstaller. I would try removing the package using `pip` then re-installing with a specific version https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

**Comment by qqbbpsy** [comment]
> I'd suggest figuring out how to upgrade your version of pyinstaller. I would try removing the package using `pip` then re-installing with a specific version https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

thanks fixed

**Comment by qqbbpsy** [comment]
![Screenshot_2021-10-16_05-24-02](https://user-images.githubusercontent.com/45928848/137582342-e9b50923-ec37-4103-b818-44cc59a5360b.png)

**Comment by KingAkeem** [comment]
All of the dependencies are not global. If you'd like to install the Python dependencies then you can use `poetry`  https://python-poetry.org/docs/basic-usage/. Either `poetry install` to download the dependencies or `poetry update` to update them. Once they've been updated/installed, you should be able to run the torBot executable. I will add this to the PR for later users.

**Comment by osmanw** [comment]
> ![image](https://user-images.githubusercontent.com/72598279/145462835-c0dea159-c360-4646-9889-98d37a272de3.png) I have installed poetry and also installed requirements by `poetry install` but it still cannot run from executable form neither .py form. How can i solve that ?

I have solve that with running it by poetry. You can try those commands 
`cd src && poetry run python torBot.py -h`
or run with python3
`cd src && poetry run python3 torBot.py -h`

**Comment by EdgyIndexer** [comment]
Maybe this will help. On Kali it looks like python3-pyinstaller was a much older version like @qqbbpsy said. Once I uninstalled that using apt remove python3-pyinstaller, that fixed it since there were versions on the machine. After that was removed it resorted to the updated one that was installed by python3.

**Comment by PSNAppz** [comment]
ete3 has been disabled in the latest version. Please check that.
