### ISSUE TITLE
"Run the container (make sure to link the tor container as tor):"

### ISSUE THREAD

**Issue by BlAd373** [DedSecInside/TorBot#244]
Sorry my ignorance 
what i have to do?
"Run the container (make sure to link the tor container as tor):"

**Comment by KingAkeem** [comment]
Can you post a screenshot of what you're doing? or copy the exact command along with the entire error output

**Comment by BlAd373** [comment]
sudo docker run --link tor:tor --rm -ti dedsecinside/torbot                                                                                                                                                                         126 ⨯
docker: Error response from daemon: could not get container for tor: No such container: tor.
See 'docker run --help'.
