### ISSUE TITLE
docker/Dockerfile expects install.sh which doesn't exist

### ISSUE THREAD

**Issue by hortonew** [DedSecInside/TorBot#267]
**Describe the bug**
docker/Dockerfile expects install.sh which doesn't exist

**To Reproduce**
1. docker build -f docker/Dockerfile -t dedsecinside/torbot .

**Expected behavior**
- Successfully built
- Successfully tagged dedsecinside/torbot:latest

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2

**Additional context**
install.sh is not part of this repo and the README.md only suggests using install.sh in the linux section, not the Docker section.

**Comment by KingAkeem** [comment]
`install.sh` has been re-added, I didn't know it was being referenced
