### ISSUE TITLE
TorBot not searching onion sites

### ISSUE THREAD

**Issue by macgreine** [DedSecInside/TorBot#277]
Torbot provides the following when searching onion sites,
Attempting to connect to https://check.torproject.org/
Connection successful.
Tor IP Address : 23.137.251.32
Attempting to connect to http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion
Attempting to connect to https://http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion
Attempting to connect to http://http://s4k4ceiapwwgcm3mkb6e4diqecpo7kvdnfr5gg7sph7jjppqkvwwqtyd.onion
Got ConnectionError after three attempts...  Please check if the TOR service is running or not.

Downloaded poetry
downloaded installed gotor
downloaded installed torBoT
tor previously downloaded
torrc edited to have following uncommented
SocksPort 9050 # Default: Bind to localhost:9050 for local connections.
SocksPort 127.0.0.1:9050 # Bind to this address:port too.

commands 
sudo service tor start

sudo bash build.sh 
Yeilds

Pulling and creating tor network
Using default tag: latest
latest: Pulling from dperson/torproxy
Digest: sha256:d8b5f1cf24f1b7a0aa334929a264b2606a107223dd0d51eb1cda8aae6fbeec53
Status: Image is up to date for dperson/torproxy:latest
docker.io/dperson/torproxy:latest
8f305646bd8247dbd4f1a48b6249ee6d9dcc31e598563a3abadf4d57a58d855a
Starting dperson/torproxy container
87a46f5bb8327be6abfe2dc33825678a5e36fd425e09ca7d8aacc5bacf624f65

tor proxy started on port :9050

Building and starting gotor container
Sending build context to Docker daemon  11.56MB
Step 1/25 : FROM registry.semaphoreci.com/golang:1.19 as builder
 ---> 7b59a6b0604b
Step 2/25 : ENV APP_HOME /go/src/gotor
 ---> Using cache
 ---> b2ce84ba602e
Step 3/25 : WORKDIR "$APP_HOME"
 ---> Using cache
 ---> 983e91d47fe2
Step 4/25 : COPY api/ api/
 ---> Using cache
 ---> 98af53baf61a
Step 5/25 : COPY cmd/ cmd/
 ---> Using cache
 ---> 4f7f05657939
Step 6/25 : COPY internal/ internal/
 ---> Using cache
 ---> eeb591aa7420
Step 7/25 : COPY linktree/ linktree/
 ---> Using cache
 ---> e67c38d745e8
Step 8/25 : COPY go.mod .
 ---> Using cache
 ---> d567e33e0bce
Step 9/25 : COPY go.sum .
 ---> Using cache
 ---> 092410b70117
Step 10/25 : COPY docker.env .
 ---> Using cache
 ---> 9f6d02e960de
Step 11/25 : RUN go mod download
 ---> Using cache
 ---> c46b0c22b21e
Step 12/25 : RUN go mod verify
 ---> Using cache
 ---> 2539861aa913
Step 13/25 : RUN go build -o gotor cmd/main/main.go
 ---> Using cache
 ---> 4c4bd9dc57e9
Step 14/25 : FROM registry.semaphoreci.com/golang:1.19
 ---> 7b59a6b0604b
Step 15/25 : ENV APP_HOME /go/src/gotor
 ---> Using cache
 ---> b2ce84ba602e
Step 16/25 : RUN mkdir -p "$APP_HOME"
 ---> Using cache
 ---> b9a9be33e500
Step 17/25 : WORKDIR "$APP_HOME"
 ---> Using cache
 ---> 83f3a41d04ce
Step 18/25 : COPY api/ .
 ---> Using cache
 ---> fd1a11b350aa
Step 19/25 : COPY linktree/ .
 ---> Using cache
 ---> 9e116b38ea20
Step 20/25 : COPY internal/ .
 ---> Using cache
 ---> 8ae11ecb88cf
Step 21/25 : COPY cmd/ cmd/
 ---> Using cache
 ---> e762d19a6b44
Step 22/25 : COPY docker.env  .env
 ---> Using cache
 ---> 37618d962ff2
Step 23/25 : COPY --from=builder "$APP_HOME"/gotor $APP_HOME
 ---> Using cache
 ---> eaac1635bc14
Step 24/25 : EXPOSE 8081
 ---> Using cache
 ---> 04d7524acc59
Step 25/25 : CMD ["./gotor", "-server"]
 ---> Using cache
 ---> 38c34ff64a0c
Successfully built 38c34ff64a0c
Successfully tagged gotor:latest
9cf439681a86896baf28f74df1c89af36aa94ab6493c15e6ff049453b45dd2b2

gotor container started on port :8081

command line 
└─$ go run cmd/main/main.go -l http://marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion -d 2 -o json
{"level":"info","ts":"2023-05-25T14:34:22.910Z","caller":"logger/logger.go:26","msg":"connecting to tor","host":"127.0.0.1","port":"9050"}
{"level":"info","ts":"2023-05-25T14:34:22.910Z","caller":"logger/logger.go:26","msg":"starting tree with root","root":"http://marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion","depth":2,"output":"json"}
{"level":"warn","ts":"2023-05-25T14:36:22.557Z","caller":"logger/logger.go:30","msg":"unable to get url","url":{"url":"http://marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion","status_code":0,"status":"","children":null},"error":"Get \"http://marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion\": socks connect tcp 127.0.0.1:9050->marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion:80: unknown error TTL expired"}

torbot fails with above message after entering following query
sudo python3 torBot.py -u marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion -s -l
or
sudo python3 torBot.py -u http://marxists3va6eopxoeiegih3iyex2zg3tmace7afbxjqlabmranzjjad.onion -s -l

I expected to see a list or representation of links by other sites to this onion url.

Using ASUS Laptop
 - OS Kali Linux 2023-1 LIVE
 - Firefox 102.8.0esr
 
I suspect torrc configuration issue although torbot gets tor node ipaddress

**Comment by KingAkeem** [comment]
I'll investigate this within the next week and let you know what I find. I may require some more information, but I think you've provided sufficient details.
