### ISSUE TITLE
[FEATURE_REQUEST] Save to File Feature

### ISSUE THREAD

**Issue by y-mehta** [DedSecInside/TorBoT#29]
Hello, I would like to add save to JSON feature in TorBoT. 
Should I directly make changes in core modules or I should create a new Module? 

Thanks.

**Comment by agrepravin** [comment]
Better you create new module.

**Comment by PSNAppz** [comment]
@y-mehta You can definitely create a new module for this and give a pull request to `dev` branch once you feel its good to go.

_Feel free to contact us for any help._
