### ISSUE TITLE
Move log level from environment variable to CLI flag

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#292]
**Is your feature request related to a problem? Please describe.**
Currently, the logging level is determined by a setting in the `.env` file. 

Where the value is set within the `.env` file
https://github.com/DedSecInside/TorBot/blob/289429f94d3814d562e49b80543b8a6097ec8d2a/.env#L4

Where the value is read from the `.env` file
https://github.com/DedSecInside/TorBot/blob/289429f94d3814d562e49b80543b8a6097ec8d2a/torbot/modules/config.py#L20-L27

**Describe the solution you'd like**
Instead of reading the value from the `.env` file, it can be read from the CLI flag using a verbose flag `-v`.

**Comment by dargudear** [comment]
I would like to work on this issue. Can you pleaseassign it to me?

**Comment by PSNAppz** [comment]
@dargudear Great!. I'll assign it to you. Raise a PR to the dev branch once you're done.

**Comment by PSNAppz** [comment]
@dargudear Any updates on this one?

**Comment by vedant-z** [comment]
@PSNAppz @KingAkeem I have come up with some initial solution for this. If you allow me then I will make PR for this issue.

**Comment by KingAkeem** [comment]
@vedant-z It's all yours, we haven't heard anything back from @dargudear.

**Comment by KingAkeem** [comment]
I've assigned the issue to you @vedant-z, thank you for the contribution in advance.

**Comment by dark-developer15** [comment]
Hey there @KingAkeem , I have made the changes, as mentioned, and am testing it. If I may, I would like to contribute to this issue.

**Comment by KingAkeem** [comment]
@dark-developer15 A pull request has already been created by @vedant-z

**Comment by dark-developer15** [comment]
Yes @KingAkeem, I saw it, I was just trying to solve it and was successful, that's why I asked.

**Comment by KingAkeem** [comment]
@dark-developer15 you can push a PR as well, I'll merge the first correct one.

**Comment by dark-developer15** [comment]
Okk sure, I'll do it. But if @vedant-z PR is good to go then, his PR should get merged, Hacktoberfest is about learning and he is doing his best 😅

**Comment by PSNAppz** [comment]
@dark-developer15 Why don't you look into #270?
