### ISSUE TITLE
TorBot Installation Issue

### ISSUE THREAD

**Issue by Balloon666** [DedSecInside/TorBot#295]
**Describe the bug**
I have followed the guidance of the readme section in "https://github.com/DedSecInside/TorBot?tab=readme-ov-file#gotor" to install the gotor and torbot. However, When I tried to run the Tool to scrawl webpages, it shows " ModuleNotFoundError: No module named 'treelib'" and "AttributeError: module 'logging' has no attribute 'getLevelNamesMapping'".

**To Reproduce**
1. Open one terminal to start tor using "sudo service tor start"
2. Open another terminal, cd to gotor/cmd/main/gotor.go and run "go run gotor.go -server". (there is no main.go in the folder, it has gotor.go instead)
3. See exit status 1
4. In the tor terminal, run "poetry install"
5. Then "poetry run python3 run.py -u https://github.com/DedSecInside/TorBot?tab=readme-ov-file#gotor"
6. See the error "AttributeError: module 'logging' has no attribute 'getLevelNamesMapping'“
7. Try to use another approach to run "python3 -m torbot -u https://github.com/DedSecInside/TorBot?tab=readme-ov-file#gotor"
8. See the error "ModuleNotFoundError: No module named 'treelib'"

**Screenshots**
1. Gotor terminal
![image](https://github.com/DedSecInside/TorBot/assets/144960008/781d41ec-220a-4aa1-8dcf-59a653fe97b3)
2. Tor and run torbot terminal
![image](https://github.com/DedSecInside/TorBot/assets/144960008/2c93ca4e-0ff3-47d6-8e2d-dde0ca0ff893)
![image](https://github.com/DedSecInside/TorBot/assets/144960008/fd58939d-1e86-4eb5-97aa-5d16056d0161)

**Desktop (please complete the following information):**
 - OS: ubuntu

**Additional context**
I have been grappling with this installation issue for approximately two weeks. Would it be possible for us to schedule a troubleshooting meeting? Really appreciate!!!

**Comment by PSNAppz** [comment]
@Balloon666 Please join our slack channel if you need help with the setup. You can join using this link: [here](https://join.slack.com/t/dedsec-inside/shared_invite/zt-i4jcgj8w-1ecHiSdRubwuppAzz8~yfg)

**Comment by KingAkeem** [comment]
Thanks @PSNAppz, closing this now. @Balloon666 join the channel if you want to go over installation.

**Comment by imabhisht** [comment]
@Balloon666 Have you able to fix  this issue??
