### ISSUE TITLE
Does it store to a DB>

### ISSUE THREAD

**Issue by WilliamJamesDalrympleWest** [DedSecInside/TorBoT#30]
Does it store the results to a db>

**Comment by PSNAppz** [comment]
@WilliamJamesDalrympleWest No. We haven't implemented that feature yet. But it will be implemented in the future versions. If you are interested you can contribute.

**Comment by PSNAppz** [comment]
@WilliamJamesDalrympleWest Closing this issue. Feel free to reopen this issue if there is any thing more to know. 

_Thank You_,
_PSN_
