### ISSUE TITLE
Move markdown files to a docs directory

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#304]
Similar to https://github.com/DedSecInside/TorBot/issues/303, but refers to markdown files or files that end with the `.md` extension (excluding README.md). These should be moved to a new directory named `docs`.

**Comment by shaswat-satyam** [comment]
Please assign this to me !

**Comment by PSNAppz** [comment]
@shaswat-satyam Sure! Please create a PR once you are done with the changes.
