### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#319]
Create a docker file to build and run torbot as a container.

**Comment by SasikaSankalana** [comment]
Would love to work on this issue. Can you assign me?

**Comment by KingAkeem** [comment]
@SasikaSankalana All yours

**Comment by KingAkeem** [comment]
There needs to be a tor network as part of the docker image and the port is specified within the `.env` file. 

https://github.com/DedSecInside/TorBot/blob/dev/.env
