### ISSUE TITLE
[Docs]:- Adding Contributors Section to the readme.md 

### ISSUE THREAD

**Issue by mohitd404** [DedSecInside/TorBot#320]
**Is your feature request related to a problem? Please describe.**

A "Contributors" section in a README.md file is important as it acknowledges and highlights the people who have contributed to the project. It fosters a sense of community, gives credit to contributors, and can attract more contributors by showing that the project is active and open to collaboration.

**Describe the solution you'd like**
adding contributors section to the readme.md file using contri.rocks

**Additional context**
demo image:-

![3](https://github.com/DedSecInside/TorBot/assets/146939900/b8dcc197-5d28-4322-82b0-d80f851bff90)

**Comment by mohitd404** [comment]
@KingAkeem i would love to work on this issue !! kindly assign me this issue.

**Comment by PSNAppz** [comment]
@mohitd404 I wanted something like this for a very long time and I got too lazy to work on this. This is all yours. I'm assigning this to you.

**Comment by PSNAppz** [comment]
On our homepage, we currently have a similar feature, but it doesn't display all the contributors. I believe that every contribution is valuable and I want everyone to recognize that.
