### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by Kalyanimhala** [DedSecInside/TorBoT#332]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/DedSecInside/TorBot/assets/147402107/7a465982-add1-494a-826e-ff30f3c37534)

**Comment by Kalyanimhala** [comment]
@KingAkeem  Kindly Assign me this issue, I want to work on it. Thank You!!

**Comment by KingAkeem** [comment]
Already exists. https://github.com/DedSecInside/TorBot?tab=readme-ov-file#all-thanks-to-our-contributors

**Comment by Kalyanimhala** [comment]
Okay, Thanks!

**Comment by KingAkeem** [comment]
No problem 👍🏿
