### ISSUE TITLE
Can't actually find the bug to correct it.

### ISSUE THREAD

**Issue by AnonymousRonin** [DedSecInside/TorBoT#341]
Got this error after installing requirements.txt 

ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    numpy~=1.24.4 from https://files.pythonhosted.org/packages/22/97/dfb1a31bb46686f09e68ea6ac5c63fdee0d22d7b23b8f3f7ea07712869ef/numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from -r requirements.txt (line 261))           

Here's the contents of requirements.txt 
numpy~=1.24.4
beautifulsoup4~=4.11.1
sklearn~=0.0
scikit-learn~=1.3.0
httpx~=0.25.0
yattag~=1.15.1
termcolor~=1.1.0
python-dotenv~=0.20.0
Unipath~=1.1
validators~=0.20.0
phonenumbers~=8.13.22
tabulate~=0.9.0
treelib~=1.7.0
toml~=0.10.2

  This I couldn't find anywhere nor could I navigate to it.
https://files.pythonhosted.org/packages/22/97

I am using Python3.11.  I don't remember seeing 3.4 was "required" so I didn't download it.

**Comment by KingAkeem** [comment]
@PSNAppz made some updates that broke the dependencies, it's been fixed. Pull new changes and try again. If it's still not working, open a new ticket. Use the `dev` branch.
