### ISSUE TITLE
Create a Wiki Page

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBoT#37]
**_Hello,_**
_You are welcome to create a new wiki page for our project. The page should include almost every details of our project including usage,contribution guidelines and CHANGELOG.  Please read the wiki guide before making a wiki page. For more information comment on this issue._
[Wiki Guide](https://guides.github.com/features/wikis/)

**Comment by Agostinelli** [comment]
I have added the wiki pages to my fork. Please review them.  Bye 👍 
[wiki pages](https://github.com/Agostinelli/TorBoT/wiki)

**Comment by PSNAppz** [comment]
@Agostinelli Good work. Some edits to be done before making a PR 

- Add yourself as a contributor 

- Add a link to License.md

**Comment by Agostinelli** [comment]
Done 👍

**Comment by PSNAppz** [comment]
Great 👏🏻, you can give a PR to dev branch once you are done. 👍🏻

**Comment by Agostinelli** [comment]
I don't think it is possible. I cannot give PR with only wiki. Any workaround?

**Comment by Agostinelli** [comment]
Could you enable collaborators to edit the wiki? In that way I will be able to copy the content.

**Comment by PSNAppz** [comment]
Oh ok @Agostinelli I will add you as a collaborator

**Comment by PSNAppz** [comment]
@Agostinelli Try now

**Comment by Agostinelli** [comment]
Yes, I am able to edit it now!

**Comment by Agostinelli** [comment]
I have copied all the content from my fork, however I cannot create a sidebar file. Try do it by yourself. Here is the code to put in the file:

```
[Home](https://github.com/DedSecInside/TorBoT/wiki) <br >
[Configuration](https://github.com/DedSecInside/TorBoT/wiki/Configuration)<br >
[Usage](https://github.com/DedSecInside/TorBoT/wiki/Usage)<br >
[Changelog](https://github.com/DedSecInside/TorBoT/wiki/Changelogs)<br >
[Credits and License](https://github.com/DedSecInside/TorBoT/wiki/Credits-and-License)
```

**Comment by PSNAppz** [comment]
@Agostinelli Ok updated 👏🏻 Thanks for the contribution.
