### ISSUE TITLE
Save to DB

### ISSUE THREAD

**Issue by y-mehta** [DedSecInside/TorBot#47]
Hey, Anyone working on this feature?

**Comment by PSNAppz** [comment]
@y-mehta Save to file is already there. So if you are planning to work on this add additional arguments (for example `torbot.py -s DB` or `torbot.py -s F` for Database and file respectively) to the `torbot.py -s`  option.

**Comment by y-mehta** [comment]
Great, I'll work on this.

**Comment by PSNAppz** [comment]
@invalid-email-address Are you still on it?

**Comment by waisuan** [comment]
@PSNAppz 

Hello! I'd like to know more about the requirements for this one. What sort of DB are we talking about here?

**Comment by PSNAppz** [comment]
@waisuan sql databases (Mysql)

**Comment by PSNAppz** [comment]
@waisuan Yes.

**Comment by PSNAppz** [comment]
@waisuan Are you still on this?

**Comment by tiagoCMatias** [comment]
Is this issue still open?
I'm trying to implement this... I did another argument in the python script requesting database name, username, and password... is this ok?

**Comment by PSNAppz** [comment]
@tiagoCMatias I like your idea but, if there is an env file in which you can add the credentials that would be more organised and better rather than giving username and password every time.
