### ISSUE TITLE
-i flag ideas

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBot#55]
The -i flag is still under development and I will be listing the features which are to be implemented.

- Webpage Title
- Description of the site (By analyzing the meta data content of the page and using some mining techniques)
- Basic Reconnaissance 
- Your idea ...

**Comment by KingAkeem** [comment]
Is anyone working on this?

**Comment by Agostinelli** [comment]
Yes!

**Comment by KingAkeem** [comment]
Awesome, can't wait for the finish. If I can help in anyway, just let me know.

**Comment by KingAkeem** [comment]
Has this feature been added?

**Comment by PSNAppz** [comment]
A PR is waiting to be merged but its not complete.

**Comment by Agostinelli** [comment]
What is wrong with that PR?

**Comment by PSNAppz** [comment]
@Agostinelli I think the description part is yet to be done. Am I right?

**Comment by PSNAppz** [comment]
The PR so far looks good and will be merged soon.

**Comment by Agostinelli** [comment]
Exact. But I will implement it in another PR.

**Comment by PSNAppz** [comment]
@Agostinelli Ok cool .

**Comment by PSNAppz** [comment]
I'm thinking about some basic text mining stuff here.

**Comment by KingAkeem** [comment]
Is anyone still working on this?

**Comment by KingAkeem** [comment]
Has been merged.
