### ISSUE TITLE
- e flag not working 

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBoT#58]
@KingAkeem . See the previous version (current master) . We missed the ext flag. That is no longer in the dev branch. Please add the code for it and submit to dev before porting to 1.2 .

**Comment by waisuan** [comment]
@PSNAppz -- Hmmm. I might be mistaken here but do we still require the -e option? Seems like getweblinks.valid_url is able to handle different kinds of URL extensions during the crawl. Is the option meant for something else?

**Comment by PSNAppz** [comment]
@waisuan The crawler by default fetches only .onion domains. The -e flag can extend the list of domains by passing the domains we want to fetch if exists. There should also be `-e all` So that all the domains can be crawled. Hope you understand.

**Comment by waisuan** [comment]
@PSNAppz 

Thanks for the clarification. Looking at the 'master' code [https://github.com/DedSecInside/TorBoT/blob/master/modules/getweblinks.py#L45], it looks like the -e flag is used to _limit_ the results to a set that have extensions of type X. Is that what we're trying to achieve here? In your explanation above, we are talking about expanding the resultset to all kinds of domains (which according to the DEV branch of TorBot, is already doing [https://github.com/DedSecInside/TorBoT/blob/dev/modules/getweblinks.py#L70]. Hence, my confusion).

**Comment by PSNAppz** [comment]
@waisuan Yea what you said is right. In the master branch we tried to limit the result using  -e flag. But as our project is about tor network we should return only .onion links and as an extension we can use the -e flag .

**Comment by KingAkeem** [comment]
@waisuan Are you still working on this bug fix or can I pick it up?

**Comment by PSNAppz** [comment]
@KingAkeem Assigning this to you.
