### ISSUE TITLE
Error in getemails module

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBoT#59]
`python3 torBot.py -u https://www.rapidtables.com/web/html/mailto.html -m`
````
Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main()
  File "torBot.py", line 163, in main
    emails = getemails.getMails(html_content)
  File "/home/psn/Documents/TorBoT/modules/getemails.py", line 30, in getMails
    emails.append(email_addr[1])
IndexError: list index out of range

```

**Comment by waisuan** [comment]
Hello. Submitted a pull request for this one. Let me know what you think! Thanks.

**Comment by PSNAppz** [comment]
`Traceback (most recent call last):
  File "torBot.py", line 186, in <module>
    main(conn=True)
  File "torBot.py", line 162, in main
    emails = getemails.getMails(html_content)
  File "/home/psn/Documents/TorBoT/modules/getemails.py", line 24, in getMails
    links = soup.find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'
`
Need a fix asap

**Comment by waisuan** [comment]
Hmmm . Doesn’t seem to be related to my changes. Will take a look.

**Comment by waisuan** [comment]
Do you have a way of replicating the error, @PSNAppz ? I'm not getting anything on my side.

**Comment by PSNAppz** [comment]
@waisuan Try this one 
`python3 torBot.py -u https://www.helloaddress.com/ -m `
It has one mail id in the page but its returning 0 found.
But on the other hand this one is working perfect
`python3 torBot.py -u https://www.asianpaints.com/contact-us.html -m `

**Comment by waisuan** [comment]
I'm not getting any errors for both links...

![image](https://user-images.githubusercontent.com/10975700/36239017-6b6a6c3c-11fe-11e8-812f-16e6f06ad17c.png)

**Comment by PSNAppz** [comment]
See its returning 0 . It should return 1

**Comment by waisuan** [comment]
@PSNAppz -- I did a bit of debugging and I suspect that the issue at hand here is not bug-related. It would seem that the site that you have cited as an example is (probably) blocking visits from Tor nodes. 

You would get an "Access Denied" error when accessing the page on Tor but OK on any other non-Tor browsers:-
![image](https://user-images.githubusercontent.com/10975700/36355525-8bd28636-14dc-11e8-9f44-7fc00eba9024.png)

For more info on this:: https://tor.stackexchange.com/questions/6646/why-do-i-get-access-denied-at-certain-web-sites-when-i-didnt-last-year

**Comment by waisuan** [comment]
You can confirm this by turning https://github.com/DedSecInside/TorBoT/blob/dev/torBot.py#L108 off and running the crawler. You should be able to see the "mail" then.

**Comment by KingAkeem** [comment]
Has this issue been fixed?

**Comment by PSNAppz** [comment]
@waisuan Ok. @KingAkeem  Seems like a problem which cannot be fixed on our side.
