### ISSUE TITLE
Add more test coverage 

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#70]
We should add more checks to each test case to cover cases more thoroughly. We should add coverage for edge cases, unexpected input and etc. 

This is being addressed with #95 but we still need more test for network utilities and we should still cover more test cases.

**Comment by Agostinelli** [comment]
Yes, I was thinking the same thing to be honest.

**Comment by PSNAppz** [comment]
I agree .

**Comment by PSNAppz** [comment]
Not closing this until coverage is atleast 80%

**Comment by KingAkeem** [comment]
This is no longer being worked on if anyone wants to take a look.

**Comment by KingAkeem** [comment]
This can be broken up into a couple of tasks. 
1. Decide on testing framework
2. Decide on HTTP client mocking library or create custom mocks
3. Design necessary mocks and write unit tests

**Comment by KingAkeem** [comment]
Majority of crawling logic has been moved to https://github.com/KingAkeem/gotor
