### ISSUE TITLE
Bad configuration - Help needed

### ISSUE THREAD

**Issue by tiagoCMatias** [DedSecInside/TorBoT#72]
Hi, 
I'm new to GitHub and I found this project interesting and I would like to contribute, but after setting the tor service and running the python script I get 0 results all the time.

Can someone help me, please?

Sorry for opening an issue for this but I didn't know what else to do.

Thanks

**Comment by PSNAppz** [comment]
Hello,
First of all thank you for showing interest in contributing to our project. As you are new to github, you may find it difficult to start but its ok we will guide you through the entire contributing process. I will assign you a beginner task soon and will let you know about it.

Regards,
PSN

**Comment by tiagoCMatias** [comment]
Hi,

I'm a software developer and I can help with all the open issues, and that is my intent. I'm just having a problem setting up the project and after that, I will try to help in the other issues opened.
I just need help to setup the project correctly.
 
I'm currently developing with Windows 10, and already have Tor service and my torrc file looks like this 

`SocksPort 9050` 

I can start the python script without any error and pass it a URL but it always returns 0 results.

Is there something wrong in my configuration?

**Comment by PSNAppz** [comment]
@tiagoCMatias Unless there is an error shown while running the program, it is perfect. Which url did you give as input?
Could you please provide the arguments passed?

**Comment by tiagoCMatias** [comment]
If I try a normal URL like `google.com` it returns 0 results, but if I try an onion URL like `http://wikitjerrta4qgz4.onion/`, the program just hangs and never finishes

**Comment by tiagoCMatias** [comment]
@PSNAppz My bad I got it to work... it seems that my computer/network is to slow... I needed to let the program to work for like 5minutes to start to get results.

It's solved... Thanks

**Comment by PSNAppz** [comment]
@tiagoCMatias No prob 😊
