### ISSUE TITLE
Fix 'Duplicate Code' issue in modules\pagereader.py

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBot#87]
[CodeFactor](https://www.codefactor.io/repository/github/dedsecinside/torbot/overview/dev) found an issue: Duplicate Code

It's currently on:
[modules\pagereader.py:38-50
](https://www.codefactor.io/repository/github/dedsecinside/torbot/source/dev/modules/pagereader.py#L38)[modules\pagereader.py:81-93
](https://www.codefactor.io/repository/github/dedsecinside/torbot/source/dev/modules/pagereader.py#L81)

**Comment by SubaruSama** [comment]
I am downloading the source code and will try to fix that. By tomorrow i will post an update.

**Comment by aldokkani** [comment]
I'm going to work on this. Is that okay?

**Comment by PSNAppz** [comment]
@aldokkani Ok sure.

**Comment by PSNAppz** [comment]
@aldokkani Status?

**Comment by aldokkani** [comment]
It was merged #103

**Comment by PSNAppz** [comment]
@aldokkani Oh ok No problem .

**Comment by atlking-Novetta** [comment]
@aldokkani If you reference the issue number within the pull request then it will notify of the status of the pull request in the issue thread.
