### ISSUE TITLE
Build visualizer module

### ISSUE THREAD

**Issue by PSNAppz** [DedSecInside/TorBot#94]
* A visualizer module
*  See other OSINT tools for reference

**Comment by PSNAppz** [comment]
@KingAkeem Its better we start this one soon.
See this for reference : [Link](http://www.visualsitemapper.com/map/google.com)

**Comment by KingAkeem** [comment]
I don't really get what it's doing. Could you give me a brief explanation?

**Comment by PSNAppz** [comment]
@KingAkeem This is what I want.
<img width="664" alt="screen shot 2018-07-16 at 7 32 54 pm" src="https://user-images.githubusercontent.com/4481429/42762885-1d14fd6a-892f-11e8-9a45-ba979792a056.png">

**Comment by PSNAppz** [comment]
@KingAkeem Great work 👏
