### ISSUE TITLE
Add Documentation to Functions

### ISSUE THREAD

**Issue by KingAkeem** [DedSecInside/TorBot#97]
The code is already decently documented but we don't have full coverage yet and it would be extremely helpful since it would help us to build an API that can then easily generate docs. If you need any instructions or directions, I'd be glad to help you. We use Google Style Python Docstrings, here's a reference if needed: http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by Jacobite747** [comment]
If this issue is still open/required, I'm happy to take it on as an initial contribution to the repo?

**Comment by PSNAppz** [comment]
@Jacobite747 Yes, this is still valid. Please try to understand the code and then make a PR once you add the documentation. Please feel free to ask me or @KingAkeem if you need any help.

**Comment by PSNAppz** [comment]
Closing this issue for now.

Thank you @kishan3  and @Jacobite747 for the contribution. :)
